# Generated by Django 5.1.2 on 2024-10-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_profile'),
        ('blog', '0003_post_image'),
    ]

    operations = [
    ]
